<?php

define('MS_SELLER_STATUS_ACTIVE', 1);
define('MS_SELLER_STATUS_TOBEACTIVATED', 2);
define('MS_SELLER_STATUS_TOBEAPPROVED', 3);

define('MS_SELLER_VALIDATION_NONE', 1);
define('MS_SELLER_VALIDATION_ACTIVATION', 2);
define('MS_SELLER_VALIDATION_APPROVAL', 3);

define('MS_PRODUCT_VALIDATION_NONE', 1);
define('MS_PRODUCT_VALIDATION_APPROVAL', 2);

define('MS_PRODUCT_STATUS_APPROVED', 1);
define('MS_PRODUCT_STATUS_PENDING', 2);
define('MS_PRODUCT_STATUS_DECLINED', 3);
define('MS_PRODUCT_STATUS_DRAFT', 4);

?>