<?php

define('MS_SELLER_STATUS_ACTIVE', 1);
define('MS_SELLER_STATUS_TOBEACTIVATED', 2);
define('MS_SELLER_STATUS_TOBEAPPROVED', 3);
define('MS_SELLER_STATUS_DISABLED', 4);


define('MS_SELLER_VALIDATION_NONE', 1);
define('MS_SELLER_VALIDATION_ACTIVATION', 2);
define('MS_SELLER_VALIDATION_APPROVAL', 3);
?>